export const categoriesSchema = [
  {
    name: "Action",
    videos: [
      {
        idvideo: 1,
        title: "Movie1",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
      {
        idvideo: 2,
        title: "Movie2",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
      {
        idvideo: 3,
        title: "Movie3",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
      {
        idvideo: 4,
        title: "Movie4",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
    ],
  },

  {
    name: "Terror",
    videos: [
      {
        idvideo: 1,
        title: "Movie1",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
      {
        idvideo: 2,
        title: "Movie2",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
      {
        idvideo: 3,
        title: "Movie3",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
      {
        idvideo: 4,
        title: "Movie4",
        user: "Joyd",
        categorie: "Action",
        video: "",
        duration: "10:26",
        cover: "../images/image.png",
        description: "Description 1",
        date: "12/20/2001",
      },
    ],
  },
];
