export let userVideos = [
  {
    idvideo: 1,
    title: "Movie1",
    user: "Joyd",
    privacy: "public",
    category: ["Action"],
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
  {
    idvideo: 2,
    title: "Movie4",
    user: "Joyd",
    privacy: "private",
    category: ["Action"],
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
  {
    idvideo: 3,
    title: "Movie3",
    user: "Joyd",
    privacy: "private",
    category: ["Action", "Drama"],
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
  {
    idvideo: 4,
    title: "Movie2",
    user: "Joyd",
    privacy: "private",
    category: ["Action"],
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
];
