export const userVideos = [
  {
    idvideo: 1,
    name: "Movie1",
    user: "Joyd",
    visibility: "public",
    categorie: "Action",
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
  {
    idvideo: 2,
    name: "Movie1",
    user: "Joyd",
    visibility: "private",
    categorie: "Action",
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
  {
    idvideo: 2,
    name: "Movie1",
    user: "Joyd",
    visibility: "private",
    categorie: "Action",
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
  {
    idvideo: 2,
    name: "Movie1",
    user: "Joyd",
    visibility: "private",
    categorie: "Action",
    video: "",
    duration: "10:26",
    cover: "../images/image.jpeg",
    description: "Description 1",
    date: "12/20/2001",
  },
];
